In [1]:
import torch
import pandas as pd


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/.venv/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/.venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1080, in launch_instance
    app.start()
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/

In [2]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
x = torch.tensor([[5,5],[6,6]])
t2 = t1 * 2
t2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [3]:
t1 + t1

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [4]:
t1 * t1

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [5]:
t1 / t2

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [6]:
t1 - t2

tensor([[-1, -2, -3],
        [-4, -5, -6]])

In [7]:
torch.matmul(x,x)

tensor([[55, 55],
        [66, 66]])

In [8]:
#automatic gradient

k = torch.tensor(2.0, requires_grad = True)

z = k**2

z.backward()

print(k.grad)

tensor(4.)


In [9]:
data = {
    "feature1": [0.5, 1.5, 2.5, 3.5, 4.5, 6.0],
    "feature2": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
    "feature3": [1.5, 2.5, 3.5, 4.5, 5.5, 7.0],
    "target": [2.0, 3.0, 4.0, 5.0, 6.0, 7.0]
}

df = pd.DataFrame(data)
print(df, type(df), df.shape)

   feature1  feature2  feature3  target
0       0.5       1.0       1.5     2.0
1       1.5       2.0       2.5     3.0
2       2.5       3.0       3.5     4.0
3       3.5       4.0       4.5     5.0
4       4.5       5.0       5.5     6.0
5       6.0       6.0       7.0     7.0 <class 'pandas.DataFrame'> (6, 4)


In [10]:
x = df.drop('target', axis = 1)  # return a dataframe with dropped column
print(x, type(x), x.shape, x.values)

   feature1  feature2  feature3
0       0.5       1.0       1.5
1       1.5       2.0       2.5
2       2.5       3.0       3.5
3       3.5       4.0       4.5
4       4.5       5.0       5.5
5       6.0       6.0       7.0 <class 'pandas.DataFrame'> (6, 3) [[0.5 1.  1.5]
 [1.5 2.  2.5]
 [2.5 3.  3.5]
 [3.5 4.  4.5]
 [4.5 5.  5.5]
 [6.  6.  7. ]]


In [11]:
y = df['target']   # to select columns by its name
print(y, type(y), y.shape)

0    2.0
1    3.0
2    4.0
3    5.0
4    6.0
5    7.0
Name: target, dtype: float64 <class 'pandas.Series'> (6,)


In [12]:
x.values

array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5],
       [2.5, 3. , 3.5],
       [3.5, 4. , 4.5],
       [4.5, 5. , 5.5],
       [6. , 6. , 7. ]])

In [13]:
X = torch.tensor(x.values, dtype= torch.float32)
Y = torch.tensor(y.values, dtype= torch.float32)

print(X, x.shape)
print(Y, y.shape)

tensor([[0.5000, 1.0000, 1.5000],
        [1.5000, 2.0000, 2.5000],
        [2.5000, 3.0000, 3.5000],
        [3.5000, 4.0000, 4.5000],
        [4.5000, 5.0000, 5.5000],
        [6.0000, 6.0000, 7.0000]]) (6, 3)
tensor([2., 3., 4., 5., 6., 7.]) (6,)


In [22]:
import torch.nn as nn

layer = nn.Linear(3, 2)

print(layer.weight)
print(layer.weight.shape)

print(layer.bias)
print(layer.bias.shape)

Parameter containing:
tensor([[-0.2806,  0.5444, -0.1218],
        [ 0.1851,  0.1799, -0.2034]], requires_grad=True)
torch.Size([2, 3])
Parameter containing:
tensor([0.5528, 0.1895], requires_grad=True)
torch.Size([2])


In [25]:
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.l1 = nn.Linear(3,2)
        self.l2 = nn.Linear(2,1)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.l1(x)
        x = self.relu(x)
        x = self.l2(x)

        return x

    

In [26]:
model = SimpleNN()
print(model)

SimpleNN(
  (l1): Linear(in_features=3, out_features=2, bias=True)
  (l2): Linear(in_features=2, out_features=1, bias=True)
  (relu): ReLU()
)


In [34]:
for name, parameter in model.named_parameters():
    print(name, parameter,parameter.shape)

l1.weight Parameter containing:
tensor([[ 0.1955,  0.2978, -0.1163],
        [-0.4515, -0.3259,  0.2397]], requires_grad=True) torch.Size([2, 3])
l1.bias Parameter containing:
tensor([-0.3453, -0.1982], requires_grad=True) torch.Size([2])
l2.weight Parameter containing:
tensor([[0.1562, 0.6464]], requires_grad=True) torch.Size([1, 2])
l2.bias Parameter containing:
tensor([-0.2889], requires_grad=True) torch.Size([1])


In [38]:
predictions = model(X)
print(predictions, predictions.shape)

tensor([[-0.2889],
        [-0.2495],
        [-0.1906],
        [-0.1317],
        [-0.0729],
        [-0.0078]], grad_fn=<AddmmBackward0>) torch.Size([6, 1])


In [41]:
loss_function = nn.MSELoss()
type(loss_function)

torch.nn.modules.loss.MSELoss

In [46]:
loss = loss_function(predictions.squeeze(), Y)
print(loss, loss.shape)

tensor(24.2805, grad_fn=<MseLossBackward0>) torch.Size([])


In [47]:
loss.backward()

In [48]:
for name, parameter in model.named_parameters():
    print(name)
    print("value:")
    print(parameter)
    print("gradient:")
    print(parameter.grad)
    print()

l1.weight
value:
Parameter containing:
tensor([[ 0.1955,  0.2978, -0.1163],
        [-0.4515, -0.3259,  0.2397]], requires_grad=True)
gradient:
tensor([[-5.3451, -5.8304, -6.6804],
        [ 0.0000,  0.0000,  0.0000]])

l1.bias
value:
Parameter containing:
tensor([-0.3453, -0.1982], requires_grad=True)
gradient:
tensor([-1.3353,  0.0000])

l2.weight
value:
Parameter containing:
tensor([[0.1562, 0.6464]], requires_grad=True)
gradient:
tensor([[-9.8820,  0.0000]])

l2.bias
value:
Parameter containing:
tensor([-0.2889], requires_grad=True)
gradient:
tensor([-9.3138])

