In [1]:
import torch 

print(torch.__version__)
print(torch.backends.mps.is_available())


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/.venv/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/.venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1080, in launch_instance
    app.start()
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/

2.2.2
True


In [2]:
x = torch.tensor(7)
y = torch.tensor([1,2,4])
z = torch.tensor([[1,2,3],
                 [4,5,6]])
# print(dir(z))
# help(x)
print(x.shape, y.shape, z.shape)
print(x.ndim, y.ndim, z.ndim)
print(x.dtype, y.dtype, z.dtype)

torch.Size([]) torch.Size([3]) torch.Size([2, 3])
0 1 2
torch.int64 torch.int64 torch.int64


In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1.0, 2.0, 3.0])

c = a + b

print(c.dtype)

torch.float32


In [4]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

B = torch.tensor([
    [10, 20],
    [30, 40],
    [50, 60]
])

A @ B

tensor([[220, 280],
        [490, 640]])

In [5]:
Z = A.reshape(3,2)

print(Z)
print(Z.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [6]:
z = A.reshape(6)

print(z)
print(z.shape)

tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


In [ ]:
x = torch.tensor([1,2,3])

y = x.unsqueeze(0)
z = x.unsqueeze(1)

print(y, z)
print(z)

tensor([[1, 2, 3]]) tensor([[1],
        [2],
        [3]])


In [8]:
y = torch.tensor([
    [1, 2, 3]
])

y.shape
y.squeeze().shape
# y.squeeze(0).shape

torch.Size([3])

In [9]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
z = 3 * y

In [10]:
print(x.grad)

None


In [11]:
z.backward()

print(x.grad)

tensor(12.)


In [14]:
x = torch.tensor(2.0, requires_grad=True)

a = x * 3
b = a ** 2
c = b + 5

c.backward()
print(x)
print(a)
print(b)
print(c)
print(x.grad)
print(c.grad_fn)
print(c.grad_fn.next_functions)

tensor(2., requires_grad=True)
tensor(6., grad_fn=<MulBackward0>)
tensor(36., grad_fn=<PowBackward0>)
tensor(41., grad_fn=<AddBackward0>)
tensor(36.)
((<PowBackward0 object at 0x10ca97100>, 0), (None, 0))


In [18]:
x = torch.tensor(2.0)

a = x * 3
b = a ** 2
c = b + 5

print(x.requires_grad)
print(a.grad_fn)
print(b.grad_fn)
print(c.grad_fn)

print(x)
print(a)
print(b)
print(c)

print(c.grad_fn)

False
None
None
None
tensor(2.)
tensor(6.)
tensor(36.)
tensor(41.)
None


In [21]:
x = torch.tensor(2.0, requires_grad=True)

a = x * 3
b = a ** 2
c = b + 5

print(x, x.grad)
# print(a, a.grad_fn, a.grad)   ---> will throw a warning
print(b)
print(c)

print(c.grad_fn)
print(c.grad_fn.next_functions)

tensor(2., requires_grad=True) None
tensor(36., grad_fn=<PowBackward0>)
tensor(41., grad_fn=<AddBackward0>)
((<PowBackward0 object at 0x10ca94d90>, 0), (None, 0))


In [22]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)

y.backward()

print(x.grad)

tensor(4.)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [26]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)

y2 = x ** 3
y2.backward()    #gradients will get accumulated

print(x.grad)

tensor(4.)
tensor(16.)
