In [1]:
import torch


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/.venv/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/.venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1080, in launch_instance
    app.start()
  File "/Users/Abhijeet/Documents/coding-repos/nn-pytorch-mastery/

In [2]:
x = torch.tensor(2.0)
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)

target = torch.tensor(10.0, requires_grad=True)

learning_rate = 0.01

for _ in range(40):


    #forward pass
    pred = w * x + b

    #calculating loss
    loss = (target - pred)**2
    print(loss.data)

    # doing backpropagation
    loss.backward()

    # updating the w parameter
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    #setting up gradient zero 
    w.grad.zero_()
        
  


tensor(4.)
tensor(3.2400)
tensor(2.4964)
tensor(1.8117)
tensor(1.2184)
tensor(0.7377)
tensor(0.3800)
tensor(0.1452)
tensor(0.0246)
tensor(0.0028)
tensor(0.0596)
tensor(0.1727)
tensor(0.3192)
tensor(0.4776)
tensor(0.6293)
tensor(0.7594)
tensor(0.8573)
tensor(0.9168)
tensor(0.9360)
tensor(0.9163)
tensor(0.8625)
tensor(0.7812)
tensor(0.6805)
tensor(0.5688)
tensor(0.4544)
tensor(0.3444)
tensor(0.2449)
tensor(0.1603)
tensor(0.0933)
tensor(0.0449)
tensor(0.0148)
tensor(0.0013)
tensor(0.0019)
tensor(0.0133)
tensor(0.0321)
tensor(0.0550)
tensor(0.0788)
tensor(0.1009)
tensor(0.1192)
tensor(0.1324)


In [3]:
import torch

# Dataset
x = torch.tensor([1., 2., 3., 4., 5.])
y = torch.tensor([5., 8., 11., 14., 17.])

# Parameters
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

learning_rate = 0.01

for step in range(1000):

    # ----------------
    # Forward pass
    # ----------------
    prediction = x * w + b

    # ----------------
    # Loss
    # ----------------
    loss = ((prediction - y) ** 2).mean()

    # ----------------
    # Backpropagation
    # ----------------
    loss.backward()

    # ----------------
    # Gradient descent
    # ----------------
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # ----------------
    # Clear gradients
    # ----------------
    w.grad.zero_()
    b.grad.zero_()

    if step % 100 == 0:
        print(
            step,
            "loss =", loss.item(),
            "w =", w.item(),
            "b =", b.item()
        )

0 loss = 296.4476318359375 w = -1.2856557369232178 b = 3.1785922050476074
100 loss = 0.44935092329978943 w = 2.5662693977355957 b = 3.5659050941467285
200 loss = 0.22825570404529572 w = 2.6908721923828125 b = 3.1160495281219482
300 loss = 0.11594676971435547 w = 2.7796788215637207 b = 2.7954299449920654
400 loss = 0.058897096663713455 w = 2.842972993850708 b = 2.5669169425964355
500 loss = 0.029917797073721886 w = 2.8880839347839355 b = 2.404052257537842
600 loss = 0.015197306871414185 w = 2.9202356338500977 b = 2.287975311279297
700 loss = 0.00771968811750412 w = 2.943150520324707 b = 2.2052454948425293
800 loss = 0.003921415191143751 w = 2.959481954574585 b = 2.1462831497192383
900 loss = 0.001991919009014964 w = 2.9711222648620605 b = 2.1042580604553223


In [4]:
x = torch.tensor([1., 2., 3., 4., 5.])
y = torch.tensor([5., 8., 11., 14., 17.])

w = torch.tensor([3.0], requires_grad=True)
b = torch.tensor([2.0], requires_grad=True)

prediction = x * w + b

loss = ((prediction - y) ** 2).mean()

loss.backward()

print("PyTorch dw:", w.grad)
print("PyTorch db:", b.grad)

PyTorch dw: tensor([0.])
PyTorch db: tensor([0.])


In [9]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])

W1 = torch.randn(4, 3, requires_grad=True)
b1 = torch.zeros(4, requires_grad=True)

W2 = torch.randn(2, 4, requires_grad=True)
b2 = torch.zeros(2, requires_grad=True)

# Forward
z1 = W1 @ x + b1
a1 = torch.relu(z1)

z2 = W2 @ a1 + b2
a2 = torch.relu(z2)

target = torch.tensor([1.0, 0.0])

loss = ((a2 - target) ** 2).mean()

print("loss:", loss.item())

loss.backward()

print("W1 gradient:")
print(W1.grad)

print("b1 gradient:")
print(b1.grad)

print("W2 gradient:")
print(W2.grad)

print("b2 gradient:")
print(b2.grad)

loss: 3.978437662124634
W1 gradient:
tensor([[ 2.6851,  5.3703,  8.0554],
        [ 0.0000,  0.0000,  0.0000],
        [-2.6043, -5.2086, -7.8130],
        [ 0.0000,  0.0000,  0.0000]])
b1 gradient:
tensor([ 2.6851,  0.0000, -2.6043,  0.0000])
W2 gradient:
tensor([[18.7991,  0.0000,  7.7091,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
b2 gradient:
tensor([2.8208, 0.0000])


In [11]:
# let's learn XOR through NN

In [12]:
import torch

# -----------------------------
# Dataset
# -----------------------------

X = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
])

y = torch.tensor([
    [0.],
    [1.],
    [1.],
    [0.]
])


# -----------------------------
# Parameters
# -----------------------------

W1 = torch.randn(2, 2, requires_grad=True)
b1 = torch.zeros(2, requires_grad=True)

W2 = torch.randn(1, 2, requires_grad=True)
b2 = torch.zeros(1, requires_grad=True)


learning_rate = 0.1


# -----------------------------
# Training
# -----------------------------

for step in range(10000):

    # Forward pass

    z1 = X @ W1.T + b1
    a1 = torch.relu(z1)

    z2 = a1 @ W2.T + b2
    y_hat = torch.sigmoid(z2)


    # Binary cross entropy

    eps = 1e-7

    loss = -(
        y * torch.log(y_hat + eps)
        + (1 - y) * torch.log(1 - y_hat + eps)
    ).mean()


    # Backward pass

    loss.backward()


    # Gradient descent

    with torch.no_grad():

        W1 -= learning_rate * W1.grad
        b1 -= learning_rate * b1.grad

        W2 -= learning_rate * W2.grad
        b2 -= learning_rate * b2.grad


    # Clear gradients

    W1.grad.zero_()
    b1.grad.zero_()
    W2.grad.zero_()
    b2.grad.zero_()


    if step % 1000 == 0:
        print(
            f"step={step}, "
            f"loss={loss.item():.4f}"
        )


# -----------------------------
# Final prediction
# -----------------------------

with torch.no_grad():

    z1 = X @ W1.T + b1
    a1 = torch.relu(z1)

    z2 = a1 @ W2.T + b2
    y_hat = torch.sigmoid(z2)

    print("\nPredictions:")
    print(y_hat)

step=0, loss=0.7051
step=1000, loss=0.0505
step=2000, loss=0.0163
step=3000, loss=0.0092
step=4000, loss=0.0063
step=5000, loss=0.0047
step=6000, loss=0.0038
step=7000, loss=0.0031
step=8000, loss=0.0027
step=9000, loss=0.0023

Predictions:
tensor([[5.6876e-03],
        [9.9908e-01],
        [9.9907e-01],
        [6.4388e-04]])
