In [22]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [2]:
class Animal:

    def __init__(self, name):
        self.name = name

    def speak(self):
        print(f"{self.name}, makes a sound")

    def getup(self):
        print("Animal gets up!!!")

#Inheritence

class Dog(Animal):

    def barks(self):
        print(f"{self.name}, now BARKS!!!")


class Dragon(Animal):
    def __init__(self, name, rider):
        super().__init__(name)
        self.rider = rider

    def riderwho(self):
        print(f"{self.name}, is rider of {self.rider}")

In [3]:
cow = Animal("Cow")
cow.speak()

dog = Dog("Kalu")
dog.speak()
dog.getup()

vhagar = Dragon("Aemond","Vhagar")

vhagar.speak()
vhagar.riderwho()

Cow, makes a sound
Kalu, makes a sound
Animal gets up!!!
Aemond, makes a sound
Aemond, is rider of Vhagar


In [4]:
layer1 = nn.Linear(10, 20)

x = torch.randn(1,10);

output = layer1(x)
print(output, output.shape, x.shape)

tensor([[-0.1399,  0.8187, -0.0356, -0.0525,  0.1517, -0.5604, -0.0425, -0.8198,
          0.1264,  0.0745,  0.0027, -0.9263, -0.2494,  0.9491, -0.4158,  0.7182,
          0.3120,  0.3759, -0.5869,  0.6125]], grad_fn=<AddmmBackward0>) torch.Size([1, 20]) torch.Size([1, 10])


In [5]:

class MyModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(10, 5)
        self.layer2 = nn.Linear(5, 1)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x        

model = MyModel()
print(model.named_parameters())

for name, param in model.named_parameters():
    print(name, param.shape)
        

<generator object Module.named_parameters at 0x12c598e40>
layer1.weight torch.Size([5, 10])
layer1.bias torch.Size([5])
layer2.weight torch.Size([1, 5])
layer2.bias torch.Size([1])


In [6]:
vocab_size = 65
block_size = 8
embedding_dim = 8


token_embedding = nn.Embedding(vocab_size, embedding_dim)
token_position = nn.Embedding(block_size, embedding_dim)

k = torch.tensor([1,3,5])
pos = torch.arange(k.shape[0])



ix = token_embedding(k)
iy = token_position(pos)

print(ix, ix.shape, iy, iy.shape)

tensor([[ 1.5165, -0.1673, -0.5651,  0.9534,  0.9405, -0.3848, -0.3089,  0.1894],
        [ 0.7382,  0.6925,  0.2481, -0.5184,  0.0460,  0.1475, -0.2441,  0.1353],
        [-0.4749,  2.2810, -0.5791, -0.5817,  0.2151,  1.2089,  0.2404, -1.5647]],
       grad_fn=<EmbeddingBackward0>) torch.Size([3, 8]) tensor([[ 0.2671,  1.0473, -0.2750,  2.2870,  1.3671,  1.6833, -0.0079,  0.5013],
        [-0.9240, -0.0307,  1.6301,  1.1012,  1.1388, -0.0325, -0.5824,  1.7991],
        [ 1.0008, -0.4037, -1.4958,  0.3504,  0.5067,  0.0373,  0.3811,  0.6507]],
       grad_fn=<EmbeddingBackward0>) torch.Size([3, 8])


In [7]:


# LETS START THE LECTURE



In [8]:
with open('shakespere.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [9]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [10]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [11]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [12]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [13]:
data = torch.tensor(encode(text), dtype=torch.long)  #converted all chars into integer values
print(data.shape, data.dtype)
data[:100]

torch.Size([1115394]) torch.int64


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])

In [14]:
# DATA SPILITONG
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [15]:
block_size = 8
train_data[:block_size + 1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [16]:
x = train_data[:block_size]
y = train_data[1:block_size + 1]   #shifting by 1

print(x, y)

for i in range(block_size):
    context = x[:i+1]
    target = y[i]
    print(f"when input is {context} the target: {target}")

tensor([18, 47, 56, 57, 58,  1, 15, 47]) tensor([47, 56, 57, 58,  1, 15, 47, 58])
when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [18]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    data = train_data if split == "train" else val_data

    offsets = torch.randint(len(data) - block_size, (batch_size,))

    x = torch.stack([data[i:i+block_size] for i in offsets])
    y = torch.stack([data[i+1:i+1+block_size] for i in offsets])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


In [27]:
class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)


    def forward(self, idx, targets=None):
        
        # idx and target are both B * T shape of tensors
        logits = self.token_embedding_table(idx)   # now logis is of shape B * T * vocab_size

        if targets == None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

            return logits, loss


m = BigramLanguageModel(vocab_size)

logits, loss = m(xb, yb)

print(logits.shape, logits, loss)


torch.Size([32, 65]) tensor([[-1.0574, -0.1878, -1.6848,  ..., -0.8915, -0.2204,  0.7608],
        [-0.9344, -0.0267, -0.4144,  ...,  0.1355, -1.4978, -1.0967],
        [-0.2424, -0.4574,  0.0384,  ..., -0.7349, -0.7139, -0.3448],
        ...,
        [ 1.2295, -1.1446,  0.5722,  ..., -0.1558, -0.4181, -0.0494],
        [ 0.6518, -0.5366,  2.0544,  ...,  0.4741,  0.7203, -0.1006],
        [ 1.7857,  0.7065, -0.3942,  ..., -0.4790, -0.1036, -0.1011]],
       grad_fn=<ViewBackward0>) tensor(4.8231, grad_fn=<NllLossBackward0>)
